#!/bin/sh
#
null="> /dev/null 2>&1"
b="\033[1;34m"
g="\033[1;32m"
w="\033[0m"
sleep 2
opkg update
echo ""
echo -e $b"➤ "$w" Menginstall... "$g"Paket pendukung"$w
opkg install bash curl git git-http php7
echo ""
sleep 2
cd /www
git clone https://github.com/fyn170/myxl
cd myxl
mv myxlun /bin
mv luci/controller/myxl.lua /usr/lib/lua/luci/controller/myxl.lua
mv luci/view/myxl.htm /usr/lib/lua/luci/view/myxl.htm
chmod +x /bin/myxlun
chmod +x /usr/lib/lua/luci/controller/myxl.lua
chmod +x /usr/lib/lua/luci/view/myxl.htm
echo ""
sleep 2
rm -f /bin/myxl && rm -f /www/myxl/myxl && rm -f /www/myxl/README.md
rm -rf /www/myxl/.git && rm -rf /www/myxl/luci && rm -f /www/myxl/rm myxl
sleep 2
echo -e $b"➤ "$w" Install... "$g"Selesai"$w
echo ""
